name: Build and push docker image

# Trigger the workflow on push to main branch or pull requests to main
on:
  pull_request:
    branches:
      - 'main'

jobs:
  docker-build-and-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/app-web:latest .

    - name: Test Docker image
      run: |
        docker run -d -p 80:80 ghcr.io/${{ github.repository_owner }}/app-web:latest
        # Wait a bit for the container to start and then test it
        sleep 5
        curl --silent --fail http://localhost:80 || exit 1
        docker stop $(docker ps -q)
