name: Build and check docker image

permissions:
  actions: read
  contents: read
  packages: write
  deployments: read
  issues: write
  pull-requests: read
  statuses: write

# Trigger the workflow on push to main branch or pull requests to main
on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/app-web:dev-latest .

    - name: Test Docker image
      run: |
        docker run -d -p 80:80 ghcr.io/${{ github.repository_owner }}/app-web:dev-latest
        # Wait a bit for the container to start and then test it
        sleep 5
        curl --silent --fail http://localhost:80 || exit 1
        docker stop $(docker ps -q)
